import type { Metadata } from "next";
import NavBar from "../../res/navbar";
import "../../global.css";
import Head from 'next/head'
import Footer from "../../res/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>My page stitle</title>
        <meta property="og:title" content="My page title" key="title" />
      </Head>
      <body>
        <NavBar/>
        <div> {/* Margem superior para o conteúdo */}
          {children}
        </div>
        <Footer />
      </body>
      
    </html>
  );
}
